apiVersion: apps/v1
kind: Deployment
metadata:
  name: practitioner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practitioner-service
  template:
    metadata:
      labels:
        app: practitioner-service
    spec:
      containers:
        - name: practitioner-service
          image: practitioner-service:1.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:mem:practitionerdb
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/